name: Infrastructure Dev

on:
  push:
    branches: [ main ]
    paths:
      - 'Infrastructure/env/dev/**'
      - 'Infrastructure/modules/**'
      - '.github/workflows/infrastructure-dev.yml'
  workflow_dispatch:

env:
  TF_VERSION: 1.0.8
  TF_ENV: dev

jobs:
  terraform-plan:
    environment: Dev-Staging
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      TF_IN_AUTOMATION: true
      azure_creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

    steps:
    - uses: actions/checkout@v2

    - id: get_acr
      name: Get ACR Info
      uses: ./.github/actions/get-acr
      with:
        resource_group: Demo-Global
        azure_creds: ${{ env.azure_creds }}

    - name: Terraform Plan
      uses: ./.github/actions/tf-plan
      with:
        terraform_version: ${{ env.TF_VERSION }}
        terraform_environment: dev
        terraform_additional_arguments: "-var 'acr_id=${{ steps.get_acr.outputs.id }}'"
        azure_creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

  terraform-apply:
    needs: terraform-plan
    if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
    environment: Dev-Infra
    concurrency: Dev-Infra
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      TF_IN_AUTOMATION: true
      azure_creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

    steps:
    - uses: actions/checkout@v2
    
    - id: get_acr
      name: Get ACR Info
      uses: ./.github/actions/get-acr
      with:
        resource_group: Demo-Global
        azure_creds: ${{ env.azure_creds }}

    - name: Terraform Apply
      uses: ./.github/actions/tf-apply
      with:
        terraform_version: ${{ env.TF_VERSION }}
        terraform_environment: dev
        terraform_additional_arguments: "-var 'acr_id=${{ steps.get_acr.outputs.id }}'"
        azure_creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
