name: Infrastructure Prod

on:
  push:
    branches: [ main ]
    paths:
      - 'Infrastructure/env/prod/**'
      - 'Infrastructure/modules/**'
      - '.github/workflows/infrastructure-prod.yml'
  workflow_dispatch:

env:
  TF_VERSION: 1.0.8
  TF_ENV: prod

jobs:
  terraform-plan:
    environment: Prod-Staging
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      TF_IN_AUTOMATION: true

    steps:
    - uses: actions/checkout@v2

    - name: Terraform Plan
      uses: ./.github/actions/tf-plan
      with:
        terraform_version: ${{ env.TF_VERSION }}
        terraform_environment: prod
        azure_creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

  terraform-apply:
    needs: terraform-plan
    if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
    environment: Prod-Infra
    concurrency: Prod-Infra
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      TF_IN_AUTOMATION: true

    steps:
    - uses: actions/checkout@v2
    
    - name: Terraform Apply
      uses: ./.github/actions/tf-apply
      with:
        terraform_version: ${{ env.TF_VERSION }}
        terraform_environment: prod
        azure_creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
